version: '3.5'

services:
  portefeuille-actions-dev:
    container_name: portefeuille-actions-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
  portefeuille-actions-test:
    container_name: portefeuille-actions-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    command: ["ng", "test"]

